finished k8s charts for eth2 with prysm

diff --git a/charts/geth-prysm/templates/prysm-beacon.deployment.yaml b/charts/geth-prysm/templates/prysm-beacon.deployment.yaml
--- a/charts/geth-prysm/templates/prysm-beacon.deployment.yaml
+++ b/charts/geth-prysm/templates/prysm-beacon.deployment.yaml
@@ -1,27 +1,15 @@
 apiVersion: apps/v1
 kind: Deployment 
 metadata:
-  name: {{ template "ethereum.fullname" . }}-{{ .Values.prysm.beacon.name }}
-  labels:
-    app: {{ template "ethereum.fullname" . }}-{{ .Values.prysm.beacon.name }}
-    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
-    release: {{ .Release.Name }}
-    heritage: {{ .Release.Service }}
+  name: {{ .Values.prysm.beacon.name }}
 spec:
-  replicas: 1
   selector:
     matchLabels:
-      app: {{ template "ethereum.fullname" . }}-{{ .Values.prysm.beacon.name }}
-      release: {{ .Release.Name }}
+      app: {{ .Values.prysm.beacon.name }}
   template:
     metadata:
       labels:
-        app: {{ template "ethereum.fullname" . }}-{{ .Values.prysm.beacon.name }}
-        release: {{ .Release.Name }}
-      annotations:
-        {{- range $key, $value := .Values.podAnnotations }}
-        {{ $key }}: {{ $value | quote }}
-        {{- end }}
+        app: {{ .Values.prysm.beacon.name }}
     spec:
       volumes:
       - name: chain-state
@@ -29,10 +17,10 @@ spec:
           claimName: {{ .Values.storage.claim }}
       - name: geth-config
         configMap:
-          name: {{ template "ethereum.fullname" . }}-geth-config          
+          name: geth-config   
       - name: prysm-config
         configMap:
-          name: {{ template "ethereum.fullname" . }}-prysm-config                  
+          name: prysm-config                  
       containers:
         - name: {{ .Values.prysm.beacon.name }}
           image: {{ .Values.prysm.beacon.image.repository }}:{{ .Values.prysm.beacon.image.tag }}
@@ -47,12 +35,14 @@ spec:
             - "--chain-id={{ .Values.general.networkId }}"
             - "--rpc-host=0.0.0.0"
             - "--grpc-gateway-host=0.0.0.0"
-            - "--execution-endpoint=http://{{ template "ethereum.fullname" . }}-{{ .Values.geth.name }}:{{ .Values.geth.ports.execution }}"
+            - "--execution-endpoint=http://{{ .Values.geth.name }}-svc:{{ .Values.geth.ports.execution }}"
             - "--accept-terms-of-use"
             - "--jwt-secret={{ .Values.shared.jwtSecretFile }}"
-            - "--suggested-fee-recipient=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
+            - "--suggested-fee-recipient={{ .Values.prysm.shared.feeRecipent }}"
             - "--minimum-peers-per-subnet=0"
             - "--enable-debug-rpc-endpoints"           
+            - "--force-clear-db"
+            - "--interop-eth1data-votes"
           resources:
             requests:
               memory: {{ .Values.prysm.beacon.resources.requests.memory }}
@@ -76,34 +66,36 @@ spec:
             - name: prysm-config
               mountPath: {{ .Values.prysm.shared.configFile }}
               subPath: config.yml         
-          # for some reason doesn't work                            
+          # for some reason doesn't work, the pod is never ready :/                         
           # readinessProbe:
-          #     httpGet:
-          #       path: /healthz
-          #       port: 8080
-          #   initialDelaySeconds: 5
-          #   periodSeconds: 5   
+          #   httpGet:
+          #     path: /healthz
+          #     port: 8080
+          #   initialDelaySeconds: 20
+          #   periodSeconds: 5
+          #   timeoutSeconds: 120
           # livenessProbe:
-          #     httpGet:
-          #       path: /healthz
-          #       port: 8080
+          #   httpGet:
+          #     path: /healthz
+          #     port: 8080
           #   initialDelaySeconds: 5
-          #   periodSeconds: 5                                       
+          #   periodSeconds: 5         
+          #   timeoutSeconds: 5                              
+          #   failureThreshold: 2
       initContainers:
         - name: wait-for-geth
           image: {{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}
           imagePullPolicy: {{ .Values.imagePullPolicy }} 
-          command: ["/bin/sh", "-c", 'until nc -z -v {{ template "ethereum.fullname" . }}-{{ .Values.geth.name }} {{ .Values.geth.ports.execution }}; do sleep 2; done']
-
-{{- with .Values.nodeSelector }}
-      nodeSelector:
-{{ toYaml . | indent 8 }}
-{{- end }}
-{{- with .Values.affinity }}
-      affinity:
-{{ toYaml . | indent 8 }}
-{{- end }}
-{{- with .Values.tolerations }}
-      tolerations:
-{{ toYaml . | indent 8 }}
-{{- end }}
+          command:
+          - "/bin/sh"
+          - "-c"
+          - >
+            timeout 900 sh -c '
+              start_time=$(date +%s)
+              while ! nc -z -v {{ .Values.geth.name }}-svc {{ .Values.geth.ports.execution }}; do
+                current_time=$(date +%s)
+                elapsed_time=$((current_time - start_time))
+                remaining_time=$((900 - elapsed_time))
+                echo "Waiting for Geth (Remaining time: $remaining_time seconds)..."
+                sleep 2
+              done'
